-- Generated by node-lua-distiller(version: 0.2.3)  at Wed Jan 08 2020 02:16:38 GMT-0800 (Pacific Standard Time)

---------------------------------------


if __DISTILLER == nil then
  __DISTILLER = nil
  __DISTILLER = {
    FACTORIES = { },
    __nativeRequire = require,
    require = function(id)
      assert(type(id) == "string", "require invalid id:" .. tostring(id))
      if package.loaded[id] then
        return package.loaded[id]
      end
      if __DISTILLER.FACTORIES[id] then
        local func = __DISTILLER.FACTORIES[id]
        package.loaded[id] = func(__DISTILLER.require) or true
        return package.loaded[id]
      end
      return __DISTILLER.__nativeRequire(id)
    end,
    define = function(self, id, factory)
      assert(type(id) == "string", "invalid id:" .. tostring(id))
      assert(type(factory) == "function", "invalid factory:" .. tostring(factory))
      if package.loaded[id] == nil and self.FACTORIES[id] == nil then
        self.FACTORIES[id] = factory
      else
        print("[__DISTILLER::define] module " .. tostring(id) .. " is already defined")
      end
    end,
    exec = function(self, id)
      local func = self.FACTORIES[id]
      assert(func, "missing factory method for id " .. tostring(id))
      func(__DISTILLER.require)
    end
  }
end



---------------------------------------


__DISTILLER:define("FDMM_Config", function(require)
env.info("---FDMM_Config Start---");

env.info("this should work3");

env.info("---FDMM_Config End---");

end)



---------------------------------------


__DISTILLER:define("FDMM_PortOps", function(require)
env.info("---FDMM_PortOps Start---");

env.info("this should work5");

env.info("---FDMM_PortOps End---");

end)



---------------------------------------


__DISTILLER:define("FDMM_MissionStart.lua_distilled", function(require)
env.info("---FDMM_MissionStart Start---");

require('FDMM_Config');
require('FDMM_PortOps');

env.setErrorMessageBoxEnabled(false);

do
  
end

env.info("---FDMM_MissionStart End---");

end)



---------------------------------------


__DISTILLER:exec("FDMM_MissionStart.lua_distilled")